/**
 * Niche Bending Engine — uses Claude API to generate intelligent niche bend suggestions.
 * Detects candidate niche via word frequency, matches bend strategies,
 * then calls Claude to generate contextually appropriate titles and reasoning.
 */

const Anthropic = require('@anthropic-ai/sdk');

// Narrative/rhetorical words common in clickbait — NOT actual topics
const NARRATIVE_WORDS = new Set([
  'revealed', 'reveals', 'reveal', 'exposed', 'exposing', 'expose',
  'hidden', 'secret', 'secrets', 'truth', 'banned', 'shocking',
  'disturbing', 'terrifying', 'dangerous', 'mysterious', 'unknown',
  'strange', 'weird', 'warning', 'finally', 'actually', 'really',
  'nobody', 'everyone', 'everything', 'nothing', 'discovered',
  'forgotten', 'controversial', 'illegal', 'untold', 'impossible',
  'incredible', 'unbelievable', 'insane', 'crazy', 'entire', 'world',
  'shocked', 'prove', 'proved', 'proven', 'wrong', 'right', 'real',
  'fake', 'true', 'false', 'explain', 'explained', 'explaining',
  'thought', 'think', 'knew', 'know', 'knows', 'known', 'told',
  'said', 'says', 'made', 'make', 'makes', 'came', 'come', 'comes',
  'found', 'find', 'finding', 'show', 'shows', 'showed', 'showing',
  'looked', 'look', 'looks', 'looking', 'want', 'wants', 'wanted',
  'need', 'needs', 'needed', 'took', 'take', 'takes', 'taking',
  'gave', 'give', 'gives', 'went', 'goes', 'going', 'gone',
  'turned', 'turn', 'turns', 'left', 'called', 'call', 'calls',
  'changed', 'change', 'changes', 'story', 'stories', 'happened',
  'happens', 'happening', 'years', 'year', 'days', 'time', 'times',
  'people', 'person', 'things', 'thing', 'fact', 'facts', 'reason',
  'reasons', 'part', 'full', 'ever', 'back', 'just', 'like',
  'documentary', 'history', 'archive', 'channel', 'video', 'videos',
  'subscribe', 'share', 'comment', 'episode', 'series',
]);

const STOP_WORDS = new Set([
  'the', 'and', 'but', 'for', 'are', 'not', 'you', 'all', 'can', 'had',
  'her', 'was', 'one', 'our', 'out', 'has', 'his', 'how', 'its', 'may',
  'new', 'now', 'old', 'see', 'way', 'who', 'did', 'get', 'got', 'let',
  'say', 'she', 'too', 'use', 'yes', 'yet', 'why', 'try', 'own', 'any',
  'few', 'off', 'set', 'two', 'run', 'put', 'end', 'big', 'ago', 'far',
  'this', 'that', 'them', 'they', 'their', 'there', 'these', 'those',
  'with', 'from', 'about', 'were', 'been', 'have', 'will', 'your',
  'more', 'most', 'than', 'very', 'what', 'when', 'where',
  'which', 'while', 'would', 'could', 'should', 'into', 'only',
  'also', 'then', 'each', 'every', 'does', 'here', 'even', 'after',
  'before', 'over', 'under', 'between', 'never', 'still',
]);

// Acronyms that should be fully uppercased
const ACRONYMS = new Set([
  'dna', 'uk', 'us', 'usa', 'nasa', 'cia', 'fbi', 'nhs', 'ceo', 'cfo',
  'ai', 'ufo', 'ufos', 'fda', 'epa', 'gmo', 'gmos', 'hiv', 'aids',
  'adhd', 'ptsd', 'bpa', 'pfas', 'mrna', 'irs', 'diy', 'nyc', 'la',
  'wwi', 'wwii', 'nato', 'opec', 'isis', 'nsa', 'dea', 'atf',
]);

/**
 * Bend strategy definitions — matched against channel content.
 * Titles are generated by Claude, not templates.
 */
const BEND_STRATEGIES = [
  // FORMAT TRANSFERS
  {
    type: 'format_transfer',
    name: 'Documentary → Home/DIY',
    sourcePatterns: ['documentary', 'explained', 'history', 'science'],
    targetNiche: 'home improvement / DIY',
    rpmEstimate: '$8-$15',
    competition: 'Low',
    briefing: 'Apply documentary-style storytelling to home improvement / DIY topics. High RPM from advertiser demand. Very few channels combine both.',
  },
  {
    type: 'format_transfer',
    name: 'Exposé → Food Safety',
    sourcePatterns: ['exposed', 'truth', 'warning', 'secret', 'hidden', 'food', 'health'],
    targetNiche: 'food safety / health',
    rpmEstimate: '$15-$30',
    competition: 'Medium',
    briefing: 'Apply exposé/investigation format to food safety and health topics. Outrage + curiosity drives massive clicks. Food/health niches command top RPM.',
  },
  {
    type: 'format_transfer',
    name: 'Mystery → Science',
    sourcePatterns: ['mystery', 'mysterious', 'unknown', 'strange', 'weird'],
    targetNiche: 'earth science / nature',
    rpmEstimate: '$8-$15',
    competition: 'Low',
    briefing: 'Apply mystery/curiosity framing to earth science or nature content. Transforms dry science into must-click content. Strong series potential.',
  },
  {
    type: 'format_transfer',
    name: 'Investigation → Corporate Exposé',
    sourcePatterns: ['crime', 'investigation', 'case', 'evidence', 'cover'],
    targetNiche: 'corporate exposé / consumer protection',
    rpmEstimate: '$10-$20',
    competition: 'Low',
    briefing: 'Apply true-crime investigation format to corporate malfeasance. Avoids saturated true crime while keeping tension/mystery hooks.',
  },

  // AUDIENCE CROSS-POLLINATION
  {
    type: 'audience_cross',
    name: 'History → Prepper/Survivalist',
    sourcePatterns: ['history', 'ancient', 'civilization', 'empire', 'collapse'],
    targetNiche: 'survival / prepper',
    rpmEstimate: '$8-$15',
    competition: 'Low',
    briefing: 'Reframe historical content for survivalist/prepper audience. Historical parallels create urgency. Preppers are engaged, high-watch-time viewers.',
  },
  {
    type: 'audience_cross',
    name: 'Science → Parents/Family',
    sourcePatterns: ['science', 'research', 'study', 'brain', 'health', 'body', 'genetic', 'dna'],
    targetNiche: 'parenting / family health',
    rpmEstimate: '$15-$25',
    competition: 'Low',
    briefing: 'Reframe science/health content for parents concerned about their children. Parenting niche has extremely high RPM. Parents click compulsively on child safety content.',
  },
  {
    type: 'audience_cross',
    name: 'Technology → Seniors',
    sourcePatterns: ['technology', 'tech', 'gadget', 'device', 'app', 'phone'],
    targetNiche: 'seniors / over 50s',
    rpmEstimate: '$10-$20',
    competition: 'Low',
    briefing: 'Reframe tech content for seniors. Massively underserved audience. High RPM from insurance/health/finance advertisers targeting 50+ demographic.',
  },

  // EMOTIONAL REFRAMES
  {
    type: 'emotional_reframe',
    name: 'DNA vs. History (Confrontational)',
    sourcePatterns: ['dna', 'genetic', 'ancestry', 'genome', 'gene'],
    targetNiche: 'same niche, confrontational framing',
    rpmEstimate: 'Same RPM, 2-3x clicks',
    competition: 'Low',
    briefing: '"DNA contradicts official history" framing. Adds conspiracy-adjacent tension without being conspiracy. Same content, dramatically higher CTR. OriginDecoder uses this angle successfully.',
  },
  {
    type: 'emotional_reframe',
    name: 'Educational → Outrage',
    sourcePatterns: ['explained', 'how', 'what', 'history of', 'the story'],
    targetNiche: 'same niche, outrage framing',
    rpmEstimate: 'Same RPM, 2-3x clicks',
    competition: 'Medium',
    briefing: 'Same educational content repackaged with outrage framing. Increases CTR 2-3x over neutral educational titles. Retains same audience.',
  },
  {
    type: 'emotional_reframe',
    name: 'Educational → Fear/Urgency',
    sourcePatterns: ['explained', 'science', 'nature', 'earth', 'environment'],
    targetNiche: 'same niche, urgency framing',
    rpmEstimate: 'Same RPM, higher CTR',
    competition: 'Medium',
    briefing: 'Transform passive educational content into urgent must-watch content. Same production, dramatically higher CTR through fear/urgency hooks.',
  },
  {
    type: 'emotional_reframe',
    name: 'Informational → Personal Stakes',
    sourcePatterns: ['product', 'review', 'consumer', 'buying', 'cost'],
    targetNiche: 'same niche, personal impact framing',
    rpmEstimate: 'Same RPM, higher engagement',
    competition: 'Low',
    briefing: 'Make content personally relevant to viewer. "This affects YOU" framing beats neutral facts. Increases watch time and engagement.',
  },

  // GEOGRAPHIC LOCALIZATION
  {
    type: 'geographic',
    name: 'US Format → Australian Market',
    sourcePatterns: ['food', 'health', 'consumer', 'exposed', 'warning', 'product'],
    targetNiche: 'Australian audience',
    rpmEstimate: '$10-$20 (AU market)',
    competition: 'Low',
    briefing: 'Adapt US-proven format for Australian audience. Less competition in AU market. Use Australian references (Woolworths, Coles, Medicare, TGA). Proven model.',
  },
  {
    type: 'geographic',
    name: 'US Format → UK Market',
    sourcePatterns: ['food', 'health', 'consumer', 'exposed', 'home', 'history'],
    targetNiche: 'UK audience',
    rpmEstimate: '$12-$22 (UK market)',
    competition: 'Low',
    briefing: 'Adapt for UK market. High RPM from strong pound and premium advertisers. Use UK references (NHS, Tesco, Sainsbury\'s). Very few faceless channels target UK specifically.',
  },

  // HYBRID TOPICS
  {
    type: 'hybrid',
    name: 'History + Conspiracy-Adjacent',
    sourcePatterns: ['history', 'ancient', 'hidden', 'forgotten', 'lost'],
    targetNiche: 'alternative history',
    rpmEstimate: '$5-$12',
    competition: 'Medium',
    briefing: 'Combine real history with mystery/conspiracy-adjacent hooks. Massive engagement. Maintain credibility while adding "forbidden knowledge" tension.',
  },
  {
    type: 'hybrid',
    name: 'Science + Horror',
    sourcePatterns: ['science', 'nature', 'ocean', 'deep', 'space', 'earth'],
    targetNiche: 'science horror / cosmic dread',
    rpmEstimate: '$5-$10',
    competition: 'Low',
    briefing: 'Apply horror framing to real science. Creates obsessive rewatch behavior. Low competition, strong thumbnail potential. Think "What scientists found terrified them."',
  },
  {
    type: 'hybrid',
    name: 'Health + Finance',
    sourcePatterns: ['health', 'medical', 'doctor', 'hospital', 'food', 'nutrition'],
    targetNiche: 'health economics / medical costs',
    rpmEstimate: '$20-$35',
    competition: 'Low',
    briefing: 'Combine health content with financial angle (cost of treatment, industry profit motives). Highest RPM niche combination possible. Both verticals attract premium advertisers.',
  },
  {
    type: 'hybrid',
    name: 'Military + Geopolitics',
    sourcePatterns: ['military', 'war', 'army', 'navy', 'soldier', 'weapon', 'battle', 'conflict', 'iran', 'china', 'russia'],
    targetNiche: 'geopolitical analysis / defense',
    rpmEstimate: '$8-$15',
    competition: 'Medium',
    briefing: 'Combine military content with geopolitical analysis. "What happens next" framing creates urgency. Defense/security audience is highly engaged and valuable to advertisers.',
  },
];

// Singleton Claude client (lazy init)
let anthropicClient = null;

function getClient() {
  if (!anthropicClient) {
    anthropicClient = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
  }
  return anthropicClient;
}

function hasOpenAiKey() {
  return !!process.env.OPENAI_API_KEY;
}

/**
 * Generate 2-3 niche bend suggestions for a high-scoring candidate.
 * Uses Claude API for contextually appropriate titles and reasoning.
 */
async function generateBends(candidate) {
  const niche = detectCandidateNiche(candidate);
  const matchedStrategies = matchBendStrategies(niche, candidate);

  if (matchedStrategies.length === 0) return [];

  // Pick top 3 strategies (diversified by type)
  const selected = diversifyBends(matchedStrategies).slice(0, 3);

  // Call Claude to generate titles and refine reasoning. If Claude is down or
  // rate-limited, use OpenAI before falling back to static strategy text.
  try {
    const enriched = await generateWithClaude(candidate, niche, selected);
    return enriched;
  } catch (err) {
    console.error(`  Claude API failed for bends (${candidate.channelTitle}): ${err.message}`);
    if (hasOpenAiKey()) {
      try {
        const enriched = await generateWithOpenAI(candidate, niche, selected);
        return enriched;
      } catch (openAiErr) {
        console.error(`  OpenAI API failed for bends (${candidate.channelTitle}): ${openAiErr.message}`);
      }
    } else {
      console.error('  OpenAI API fallback unavailable: OPENAI_API_KEY is not set.');
    }
    // Return strategies with fallback titles
    return selected.map(s => ({
      description: s.name,
      type: s.type.replace('_', ' '),
      baseNiche: niche.nicheLabel,
      targetNiche: s.targetNiche,
      whyItWorks: s.briefing,
      exampleTitles: ['(Title generation unavailable — Claude API error)'],
      estimatedCompetition: s.competition,
      rpmEstimate: s.rpmEstimate,
    }));
  }
}

/**
 * Call Claude API to generate contextually appropriate bend titles and reasoning.
 */
async function generateWithClaude(candidate, niche, strategies) {
  const topVideos = [...candidate.videos]
    .sort((a, b) => b.views - a.views)
    .slice(0, 5);

  const videoList = topVideos
    .map(v => `- "${v.title}" (${v.views.toLocaleString()} views)`)
    .join('\n');

  const strategySummaries = strategies
    .map((s, i) => `${i + 1}. **${s.name}** (${s.type.replace('_', ' ')})\n   Target: ${s.targetNiche}\n   Strategy: ${s.briefing}`)
    .join('\n\n');

  const nx = candidate.nexlev || {};
  const rpmInfo = nx.rpm ? `RPM: $${nx.rpm.toFixed(2)}` : '';
  const revenueInfo = nx.avgMonthlyRevenue ? `Monthly Revenue: $${nx.avgMonthlyRevenue.toFixed(0)}` : '';
  const outlierInfo = nx.outlierScore ? `Outlier Score: ${nx.outlierScore}x` : '';
  const categoriesInfo = (nx.categories || []).length > 0 ? `Categories: ${nx.categories.join(', ')}` : '';

  const prompt = `You are MUSE, a niche-bending strategist for a faceless YouTube automation business.

Your job: Analyze this breakout channel's viral triggers, then generate "niche bends" — ways to take the SAME viral trigger and apply it to a different subject, format, or audience for higher clicks, better RPM, or less competition.

CHANNEL: "${candidate.channelTitle}"
DETECTED NICHE: ${niche.nicheLabel}
SUBSCRIBERS: ${candidate.subscriberCount}
TOP TOPICS: ${niche.topTopics.slice(0, 6).join(', ')}
${rpmInfo ? rpmInfo + '\n' : ''}${revenueInfo ? revenueInfo + '\n' : ''}${outlierInfo ? outlierInfo + '\n' : ''}${categoriesInfo ? categoriesInfo + '\n' : ''}

TOP PERFORMING VIDEOS:
${videoList}

STEP 1 — VIRAL TRIGGER EXTRACTION:
For each top video above, identify:
- The surface topic (what the video is about)
- The viral trigger underneath (WHY people click): curiosity gap, fear, forbidden knowledge, identity, scale shock, recency, outrage, nostalgia, mystery, transformation, versus/comparison, conspiracy-adjacent, disappearance, countdown pressure, superlative
- Separability test: "If I changed the subject completely, would people still click?" (score 1-5)

STEP 2 — NICHE BENDING:
For the ${strategies.length} strategies below, use the strongest viral triggers (separability 3+) and bend them:

${strategySummaries}

For each strategy, generate:
- 2-3 working video titles (50-80 chars, natural YouTube titles that a real viewer would click)
- One-line "why it works" explanation specific to THIS niche's triggers
- Which of these channels it could work for: Food Flip (Australian health/food), Aussie Exposed (Australian consumer), Voidscape (space documentary), Dark Atlas (earth science), Crisis Alert (disaster/earth), The $1 Fix (home maintenance)
- Thumbnail direction (one sentence)
- Confidence: high, medium, or low

RULES:
- Extract the VIRAL TRIGGER, not the topic. "DNA proves historians wrong" → trigger is "authority contradiction". Bend: apply that trigger to a different subject.
- Titles must be specific and natural — not generic templates with blanks filled in
- VARY your hooks. Never use "revealed" or "exposed" more than once across all titles
- Each title must pass the "would I actually click this?" test
- The "why it works" must reference the specific viral trigger, not generic marketing advice

Respond in this exact JSON format (no markdown, no code fences, just raw JSON):
[
  {
    "strategyIndex": 0,
    "viralTriggers": ["curiosity gap", "forbidden knowledge"],
    "titles": ["Title 1", "Title 2", "Title 3"],
    "whyItWorks": "Specific explanation referencing the viral trigger.",
    "targetChannel": "Dark Atlas",
    "thumbnailDirection": "One sentence describing the thumbnail concept.",
    "confidence": "high"
  }
]`;

  const client = getClient();
  const response = await client.messages.create({
    model: process.env.ANTHROPIC_MODEL || 'claude-opus-4-20250514',
    max_tokens: 2048,
    messages: [{ role: 'user', content: prompt }],
  });

  const text = response.content[0].text.trim();

  // Parse JSON response
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    // Try extracting JSON from response if wrapped in anything
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      parsed = JSON.parse(jsonMatch[0]);
    } else {
      throw new Error('Could not parse Claude response as JSON');
    }
  }

  // Build final bend objects
  return strategies.map((strategy, i) => {
    const claudeResult = parsed.find(p => p.strategyIndex === i) || parsed[i];
    return {
      description: strategy.name,
      type: strategy.type.replace('_', ' '),
      baseNiche: niche.nicheLabel,
      targetNiche: strategy.targetNiche,
      whyItWorks: claudeResult?.whyItWorks || strategy.briefing,
      exampleTitles: claudeResult?.titles || ['(No titles generated)'],
      estimatedCompetition: strategy.competition,
      rpmEstimate: strategy.rpmEstimate,
      viralTriggers: claudeResult?.viralTriggers || [],
      targetChannel: claudeResult?.targetChannel || null,
      thumbnailDirection: claudeResult?.thumbnailDirection || null,
      confidence: claudeResult?.confidence || null,
    };
  });
}

/**
 * Capitalize a word — handles acronyms (DNA, UK, USA) and normal words.
 */
async function generateWithOpenAI(candidate, niche, strategies) {
  const topVideos = [...candidate.videos]
    .sort((a, b) => b.views - a.views)
    .slice(0, 5)
    .map(v => `- "${v.title}" (${v.views.toLocaleString()} views)`)
    .join('\n');

  const strategySummaries = strategies
    .map((s, i) => `${i}. ${s.name}: target ${s.targetNiche}. ${s.briefing}`)
    .join('\n');

  const prompt = `You are MUSE, a niche-bending strategist for Claudio's faceless YouTube automation business.

Analyze this breakout channel and generate niche-bend ideas.

CHANNEL: "${candidate.channelTitle}"
DETECTED NICHE: ${niche.nicheLabel}
SUBSCRIBERS: ${candidate.subscriberCount}
TOP TOPICS: ${niche.topTopics.slice(0, 6).join(', ')}

TOP PERFORMING VIDEOS:
${topVideos}

STRATEGIES:
${strategySummaries}

Return raw JSON only. No markdown. Format:
[
  {
    "strategyIndex": 0,
    "viralTriggers": ["curiosity gap", "forbidden knowledge"],
    "titles": ["Title 1", "Title 2", "Title 3"],
    "whyItWorks": "Specific explanation referencing the viral trigger.",
    "targetChannel": "Dark Atlas",
    "thumbnailDirection": "One sentence describing the thumbnail concept.",
    "confidence": "high"
  }
]`;

  const response = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL || 'gpt-4.1-mini',
      input: prompt,
      max_output_tokens: 2048,
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`OpenAI HTTP ${response.status}: ${body.slice(0, 300)}`);
  }

  const data = await response.json();
  const text = extractOpenAIText(data);
  if (!text) throw new Error('OpenAI response did not include text output');

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      parsed = JSON.parse(jsonMatch[0]);
    } else {
      throw new Error('Could not parse OpenAI response as JSON');
    }
  }

  return strategies.map((strategy, i) => {
    const modelResult = parsed.find(p => p.strategyIndex === i) || parsed[i];
    return {
      description: strategy.name,
      type: strategy.type.replace('_', ' '),
      baseNiche: niche.nicheLabel,
      targetNiche: strategy.targetNiche,
      whyItWorks: modelResult?.whyItWorks || strategy.briefing,
      exampleTitles: modelResult?.titles || ['(No titles generated)'],
      estimatedCompetition: strategy.competition,
      rpmEstimate: strategy.rpmEstimate,
      viralTriggers: modelResult?.viralTriggers || [],
      targetChannel: modelResult?.targetChannel || null,
      thumbnailDirection: modelResult?.thumbnailDirection || null,
      confidence: modelResult?.confidence || null,
    };
  });
}

function extractOpenAIText(data) {
  if (data.output_text) return data.output_text;
  const parts = [];
  for (const item of data.output || []) {
    for (const content of item.content || []) {
      if (content.type === 'output_text' && content.text) parts.push(content.text);
      if (content.type === 'text' && content.text) parts.push(content.text);
    }
  }
  return parts.join('\n');
}

function capitalizeWord(word) {
  if (ACRONYMS.has(word)) return word.toUpperCase();
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/**
 * Detect the candidate's primary niche from their content.
 * Filters out narrative/rhetorical words to find actual subject matter nouns.
 */
function detectCandidateNiche(candidate) {
  const allText = [
    candidate.channelTitle,
    candidate.description,
    ...candidate.videos.map(v => v.title),
  ].join(' ').toLowerCase();

  const words = allText
    .replace(/[^a-z\s]/g, '')
    .split(/\s+/)
    .filter(w => w.length > 2);

  const freq = {};
  for (const w of words) {
    if (STOP_WORDS.has(w) || NARRATIVE_WORDS.has(w)) continue;
    freq[w] = (freq[w] || 0) + 1;
  }

  const topTopics = Object.entries(freq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([word]) => capitalizeWord(word));

  const nicheLabel = topTopics.slice(0, 3).join(' / ');

  return { topTopics, nicheLabel, allText };
}

/**
 * Match bend strategies against the candidate's detected niche.
 */
function matchBendStrategies(niche, candidate) {
  const matched = [];

  for (const strategy of BEND_STRATEGIES) {
    const matchCount = strategy.sourcePatterns.filter(p =>
      niche.allText.includes(p)
    ).length;

    if (matchCount === 0) continue;

    matched.push({ ...strategy, matchStrength: matchCount });
  }

  matched.sort((a, b) => b.matchStrength - a.matchStrength);
  return matched;
}

/**
 * Ensure bend suggestions include different types when possible.
 */
function diversifyBends(bends) {
  if (bends.length <= 3) return bends;

  const selected = [];
  const usedTypes = new Set();

  for (const bend of bends) {
    if (selected.length >= 3) break;
    if (!usedTypes.has(bend.type)) {
      selected.push(bend);
      usedTypes.add(bend.type);
    }
  }

  for (const bend of bends) {
    if (selected.length >= 3) break;
    if (!selected.includes(bend)) {
      selected.push(bend);
    }
  }

  return selected;
}

module.exports = { generateBends };
